apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-datasight-hf-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ocs-storagecluster-cephfs
  resources:
    requests:
      storage: 200Gi
